### ISSUE TITLE
Base Docker image not available

### ISSUE THREAD

**Issue by keyboardsamurai** [simonmulser/simcoin#2]
`simcoin/code/docker/Dockerfile` uses `FROM simcoin/base:v1` which is not listed docker hub. So when you try to build the image it goes

```
make build-image
cd ./code/docker; \
	docker build --no-cache --tag simcoin/bitcoin:v2 .
Sending build context to Docker daemon  2.048kB
Step 1/10 : FROM simcoin/base:v1
pull access denied for simcoin/base, repository does not exist or may require 'docker login'
make: *** [build-image] Error 1
```

**Comment by simonmulser** [comment]
#3 fixes this issue. added the code of the old base image to the Dockerfile.

**Comment by simonmulser** [comment]
#3 fixes this issue. added the code of the old base image to the Dockerfile.
