### ISSUE TITLE
transaction

### ISSUE THREAD

**Issue by zrpkid** [simonmulser/simcoin#4]
Hello, I want to know do this framework contains transaction module? Or in other words, can I define my own transaction type to test my work?

**Comment by simonmulser** [comment]
you mean bitcoin tx? basically you can implement whatever event you want. currently `block` and `tx` events are implemented as you can see in [event.py](https://github.com/sbaresearch/simcoin/blob/master/code/event.py). so yes, it is already possible to create tx during a simulation. currently the tx is created manually as you can see in [node.py](https://github.com/sbaresearch/simcoin/blob/master/code/node.py). but you can also implement the normal tx creation over RPC analog to the block generation in the same file `node.py`.

happy to receive a PR for that 👍 :)

**Comment by simonmulser** [comment]
Since this is not an issue on the project itself, I will close it.
